// Add additional action types here as necessary
export const TODO_ACTION_TYPES = {
  ADD_NEW_TODO: 'ADD_NEW_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  SET_TODO_DIALOG_TEXT: 'SET_TODO_DIALOG_TEXT',
  SET_SELECTED_TODO_INDEX: 'SET_SELECTED_TODO_INDEX',
  ADD_TODO_NOTE: 'ADD_TODO_NOTE',
  REMOVE_TODO_NOTE: 'REMOVE_TODO_NOTE',
  SET_NOTE_DIALOG_TEXT: 'SET_NOTE_DIALOG_TEXT'
};
