// Add additional action types here as necessary
export const TODO_ACTION_TYPES = {
  ADD_NEW_TODO: 'ADD_NEW_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  SET_TODO_DIALOG_TEXT: 'SET_TODO_DIALOG_TEXT',
  SET_SELECTED_TODO_INDEX: 'SET_SELECTED_TODO_INDEX'
};
